<div id="login">
            <form method="post" action="" id="loginform" name="loginform">
                <h1>
                    <a title="Portal do IFSC" href="">Portal do IFSC</a>
                </h1>
                <p>
                    <label>Nome de usuário<br>
                            <input type="text" tabindex="10" size="20" value="" class="input" id="user_login" name="usuario">
                                </label>
                                </p>
                                <p>
                                    <label>
                                        Senha<br>
                                            <input type="password" tabindex="20" size="20" value="" class="input" id="user_pass" name="senha">
                                                </label>
                                                </p>
                                                <p>
                                                    <p class="submit">
                                                        <input type="submit" tabindex="100" value="Login" class="button professor" id="wp-submit" name="button">
                                                    </p>
           </form>
</div>
