<?php

$title = 'Cursos: Adicionar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cursos', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('carga_horaria'));
echo $this->formRow($form->get('descricao'));
echo $this->formRow($form->get('area_atuacao'));
echo $this->formRow($form->get('duracao_semestral'));
echo $this->formRow($form->get('turno'));
echo $this->formRow($form->get('vagas'));
echo $this->formRow($form->get('coordenador'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('telefone'));
echo $this->formRow($form->get('publico_alvo'));
echo $this->formRow($form->get('perfil_profissional'));
echo $this->formRow($form->get('certificacao'));
echo $this->formRow($form->get('forma_ingresso'));
echo $this->formRow($form->get('local'));
echo $this->formRow($form->get('projeto_pedagogico'));
echo $this->formRow($form->get('projeto_tipo'));
echo $this->formRow($form->get('projeto_nome'));
echo $this->formRow($form->get('projeto_detalhes'));
echo $this->formRow($form->get('mapa_nome_arquivo'));
echo $this->formRow($form->get('nome_arquivo'));
echo $this->formRow($form->get('nome_campus'));
echo $this->formRow($form->get('nome_nivel'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();