<?php

$title = 'Cursos IF-SC';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cursos', array('action'=>'add'));?>" class="btn btn-success">Adicionar Curso</a>
</p>

<table class="table">
<tr>
    <th>Id</th>
    <th>Curso</th>
    <th>Coordenador</th>
    <th>E-mail</th>
    <th>Telefone</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($cursosList as $curso) : ?>
<tr>
    <td><?php echo $this->escapeHtml($curso->id);?></td>
    <td><?php echo $this->escapeHtml($curso->nome);?></td>
    <td><?php echo $this->escapeHtml($curso->coordenadorcurso);?></td>
    <td><?php echo $this->escapeHtml($curso->emailcurso);?></td>
    <td><?php echo $this->escapeHtml($curso->telefonecurso);?></td>
    <td>
        <a href="<?php echo $this->url('cursos',
            array('action'=>'edit', 'id' => $cursos->id));?>" class="btn btn-mini btn-primary"><i class="icon-pencil"></i> Editar</a></a>
    </td>
    <td>
        <a href="<?php echo $this->url('cursos',
            array('action'=>'delete', 'id' => $cursos->id));?>"class="btn btn-mini btn-danger"><i class="icon-trash"></i> Deletar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
