<html lang="en">
<head>
    
   <?php echo $this->headScript()->prependFile($this->basePath() . '/js/list.js') ?> 
   
   <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                   ->prependStylesheet($this->basePath() . '/css/list.css') ?> 
	
</head>

<body align="right" style="">

	<form name="isc">
    <table width="760px" height="80">
	<tr>
		<td colspan="5" height="32px">
		<br/>
		<td>
	</tr>
	<tr>
    <td width="20px"></td>	
	<td width="180px" align="left">
<select name="example" size="1" onChange="redirect(this.options.selectedIndex)">
<option selected>Selecione seu Campus</option>
<?php foreach ($cursosList as $curso) : ?>
<option value="<?php echo $this->escapeHtml($curso->id_campus);?>"><?php echo $this->escapeHtml($curso->nome_campus);?>
</option><?php endforeach; ?>
<option value="2">Caçador</option>
<option value="3">Canoinhas</option>
<option value="4">Chapecó</option>
<option value="5">Criciúma</option>
<option value="6">Florianópolis - Continente</option>
<option value="7">Florianópolis</option>
<option value="8">Gaspar</option>
<option value="9">Itajaí</option>
<option value="10">Jaraguá do Sul</option>
<option value="11">Jaraguá do Sul (GW)</option>
<option value="12">Joinville</option>
<option value="13">Lages</option>
<option value="14">Palhoça - Bilíngue</option>
<option value="15">São José</option>
<option value="16">São Miguel do Oeste</option>
<option value="17">Xanxerê</option>
<option value="18">Urupema</option>
<option value="19">EAD</option>
<option value="20">Garopaba</option>
</select>
	</td>
    <td width="180px" align="left">
		<select name="stage2" size="1" onChange="redirect1(this.options.selectedIndex)">
		<option value=" " selected> </option>
		<option value=" " selected>Selecione a Formação</option>
		</select>
	</td>
	<td width="380px" align="left">
		<select name="stage3" size="1" onChange="redirect2(this.options.selectedIndex)">
		<option value=" " selected> </option>
		<option value=" " selected>Selecione o Curso</option>
		<?php foreach ($cursosList as $curso) : ?>
                <option value="<?php echo $this->escapeHtml($curso->id_nivel);?>"><?php echo $this->escapeHtml($curso->nome_nivel);?>
                </option><?php endforeach; ?>
		</select>
    </td>
    </tr>
    </table>
    </form>
</body>
</html>